server.port=${HTTP_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cpayadmin}
spring.datasource.username=${DB_USERNAME:cpayadmin}
spring.datasource.password=${DB_PASSWORD:cpayadmin}

spring.session.store-type=none
spring.session.timeout=15m

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=never

actuator.username=${ACTUATOR_USERNAME:admin}
actuator.password=${ACTUATOR_PASSWORD:admin}

spring.flyway.enabled=false
spring.main.allow-circular-references=true

custom.gatewaystate=${CUSTOM_GATEWAYSTATE:SANDBOX}
custom.lockfiledirectory=${CUSTOM_LOCKFILEDIRECTORY:./tmp}
custom.ssl.skip-verify=${CUSTOM_SSL_SKIP_VERIFY:false}
app.base.url=${APP_BASE_URL:http://localhost:8081}
