custom.gatewaystate=${CUSTOM_GATEWAYSTATE:PRODUCTION}
custom.ssl.skip-verify=${CUSTOM_SSL_SKIP_VERIFY:false}
cpay.legacy-dbchanges.enabled=false
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:false}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:false}
