include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: error
  exclude:
    - build/**

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: false
    directives_ordering: true
    prefer_final_locals: true
    use_build_context_synchronously: true
