server.httpport=9000

spring.datasource.url=jdbc:mysql://localhost:3306/cpayadmin
spring.datasource.username=general
spring.datasource.password=general
#spring.datasource.username=cpayadmin
#spring.datasource.password=mBG=v#MeAxs1

#mBG=v#MeAxs1
spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=create-drop


spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout.seconds=900

# The format used for the keystore. It could be set to JKS in case it is a JKS file
#server.ssl.key-store-type=PKCS12
# The path to the keystore containing the certificate
#server.ssl.key-store=classpath:keystore/springboot_letsencrypt.p12
# The password used to generate the certificate
#server.ssl.key-store-password=cpayadmin
# The alias mapped to the certificate
#server.ssl.key-alias=bootalias


mail.host=smtp.gmail.com
mail.port=587
mail.username=joseph.tabajjwa@gmail.com
mail.password=fndytfovhugpvzya
mail.properties_mail_smtp_auth=true
mail.properties_mail_smtp_starttls_enable=true

server.error.whitelabel.enabled=false


spring.mvc.static-path-pattern=/**
spring.resources.static-locations=classpath:/static/

spring.mvc.throw-exception-if-no-handler-found=false
spring.resources.add-mappings=true


#Directory to store lock files
#custom.lockfiledirectory=/opt/cpayadmin/locks/
custom.lockfiledirectory=/Users/josephtabajjwa/Desktop/Joe/projects/CitoTech/paymentgw/cpay/clientside/tests/php/locks/
#/opt/cpayadmin/locks/

#Set this to SANDBOX if you want this to be sandbox system.
#gatewaystate property is no longer useful.
custom.gatewaystate=SANDBOX

spring.flyway.group=true
spring.flyway.enabled=false