INSERT INTO `settings` (`name`, `label`, `setting_value`, `setting_group`, `description`) VALUES
('merchant_login_hero_image_url', 'Customer Login Image URL', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1600&q=80', 'Login Portal', 'Image URL used on the customer login portal left panel.'),
('merchant_login_hero_title', 'Customer Login Hero Title', 'Merchant operations workspace', 'Login Portal', 'Accessible title for the customer login portal image panel.'),
('merchant_login_hero_copy', 'Customer Login Hero Copy', 'Secure access to payments, insights, and support in one place.', 'Login Portal', 'Accessible supporting text for the customer login portal image panel.'),
('merchant_login_payments_title', 'Customer Login Payments Card Title', 'Payments', 'Login Portal', 'Title for the payments floating card on the customer login portal.'),
('merchant_login_payments_status', 'Customer Login Payments Card Status', 'Successful', 'Login Portal', 'Status line for the payments floating card on the customer login portal.'),
('merchant_login_payments_detail', 'Customer Login Payments Card Detail', 'UGX 250,000', 'Login Portal', 'Detail line for the payments floating card on the customer login portal.'),
('merchant_login_communication_title', 'Customer Login Communication Card Title', 'Communication', 'Login Portal', 'Title for the communication floating card on the customer login portal.'),
('merchant_login_communication_detail', 'Customer Login Communication Card Detail', 'New message', 'Login Portal', 'Detail line for the communication floating card on the customer login portal.'),
('merchant_login_verification_title', 'Customer Login Verification Card Title', 'Verification', 'Login Portal', 'Title for the verification floating card on the customer login portal.'),
('merchant_login_verification_detail', 'Customer Login Verification Card Detail', 'Identity verified', 'Login Portal', 'Detail line for the verification floating card on the customer login portal.'),
('merchant_login_insights_title', 'Customer Login Insights Card Title', 'Insights', 'Login Portal', 'Title for the insights floating card on the customer login portal.'),
('merchant_login_insights_detail', 'Customer Login Insights Card Detail', '+28% this month', 'Login Portal', 'Detail line for the insights floating card on the customer login portal.'),
('merchant_login_support_title', 'Customer Login Support Card Title', 'Support', 'Login Portal', 'Title for the support floating card on the customer login portal.'),
('merchant_login_support_detail', 'Customer Login Support Card Detail', 'We''re here to help', 'Login Portal', 'Detail line for the support floating card on the customer login portal.'),
('merchant_login_secure_title', 'Customer Login Secure Benefit Title', 'Secure Platform', 'Login Portal', 'Title for the secure benefit tile on the customer login portal.'),
('merchant_login_secure_copy', 'Customer Login Secure Benefit Copy', 'Enterprise-grade protection', 'Login Portal', 'Copy for the secure benefit tile on the customer login portal.'),
('merchant_login_benefit_insights_title', 'Customer Login Insights Benefit Title', 'Real-time Insights', 'Login Portal', 'Title for the insights benefit tile on the customer login portal.'),
('merchant_login_benefit_insights_copy', 'Customer Login Insights Benefit Copy', 'Data-driven decisions', 'Login Portal', 'Copy for the insights benefit tile on the customer login portal.'),
('merchant_login_control_title', 'Customer Login Control Benefit Title', 'Operational Control', 'Login Portal', 'Title for the operational control benefit tile on the customer login portal.'),
('merchant_login_control_copy', 'Customer Login Control Benefit Copy', 'Manage with confidence', 'Login Portal', 'Copy for the operational control benefit tile on the customer login portal.'),
('merchant_login_automation_title', 'Customer Login Automation Benefit Title', 'Automation Ready', 'Login Portal', 'Title for the automation benefit tile on the customer login portal.'),
('merchant_login_automation_copy', 'Customer Login Automation Benefit Copy', 'Powerful tools for efficiency', 'Login Portal', 'Copy for the automation benefit tile on the customer login portal.'),
('merchant_login_fast_title', 'Customer Login Fast Benefit Title', 'Fast', 'Login Portal', 'Title for the fast benefit tile on the customer login portal.'),
('merchant_login_fast_copy', 'Customer Login Fast Benefit Copy', 'Quick payments and settlements', 'Login Portal', 'Copy for the fast benefit tile on the customer login portal.'),
('merchant_login_reliable_title', 'Customer Login Reliable Benefit Title', 'Reliable & Scalable', 'Login Portal', 'Title for the reliable benefit tile on the customer login portal.'),
('merchant_login_reliable_copy', 'Customer Login Reliable Benefit Copy', 'Built for growth and trust', 'Login Portal', 'Copy for the reliable benefit tile on the customer login portal.'),
('merchant_login_help_title', 'Customer Login Help Benefit Title', 'Support', 'Login Portal', 'Title for the support benefit tile on the customer login portal.'),
('merchant_login_help_copy', 'Customer Login Help Benefit Copy', 'We''re here to help', 'Login Portal', 'Copy for the support benefit tile on the customer login portal.'),
('admin_login_hero_image_url', 'Admin Login Image URL', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1600&q=80', 'Login Portal', 'Image URL used on the admin login portal left panel.'),
('admin_login_hero_title', 'Admin Login Hero Title', 'Powerful control. Smarter operations.', 'Login Portal', 'Accessible title for the admin login portal image panel.'),
('admin_login_hero_copy', 'Admin Login Hero Copy', 'Manage your platform, users, and transactions with confidence and clarity.', 'Login Portal', 'Accessible supporting text for the admin login portal image panel.'),
('admin_login_approvals_title', 'Admin Login Approvals Card Title', 'Secure Platform', 'Login Portal', 'Title for the approvals floating card on the admin login portal.'),
('admin_login_users_title', 'Admin Login User Management Card Title', 'User & Role Management', 'Login Portal', 'Title for the user management floating card on the admin login portal.'),
('admin_login_analytics_title', 'Admin Login Analytics Card Title', 'Real-time Analytics', 'Login Portal', 'Title for the analytics floating card on the admin login portal.'),
('admin_login_merchant_title', 'Admin Login Merchant Oversight Card Title', 'System Management', 'Login Portal', 'Title for the merchant oversight floating card on the admin login portal.'),
('admin_login_security_title', 'Admin Login Security Card Title', 'Audit & Compliance', 'Login Portal', 'Title for the security floating card on the admin login portal.'),
('admin_login_monitoring_title', 'Admin Login Payments Monitoring Card Title', 'Payments Monitoring', 'Login Portal', 'Title for the payments monitoring floating card on the admin login portal.'),
('admin_login_support_title', 'Admin Login Support Card Title', 'Support', 'Login Portal', 'Title for the support floating card on the admin login portal.'),
('admin_login_system_title', 'Admin Login System Settings Card Title', 'System Settings', 'Login Portal', 'Title for the system settings floating card on the admin login portal.'),
('admin_login_secure_title', 'Admin Login Secure Benefit Title', 'Secure', 'Login Portal', 'Title for the secure benefit tile on the admin login portal.'),
('admin_login_secure_copy', 'Admin Login Secure Benefit Copy', 'Protect platform and data', 'Login Portal', 'Copy for the secure benefit tile on the admin login portal.'),
('admin_login_insights_title', 'Admin Login Insights Benefit Title', 'Reliable', 'Login Portal', 'Title for the insights benefit tile on the admin login portal.'),
('admin_login_insights_copy', 'Admin Login Insights Benefit Copy', 'High availability and performance', 'Login Portal', 'Copy for the insights benefit tile on the admin login portal.'),
('admin_login_control_title', 'Admin Login Control Benefit Title', 'Insightful', 'Login Portal', 'Title for the control benefit tile on the admin login portal.'),
('admin_login_control_copy', 'Admin Login Control Benefit Copy', 'Real-time reports and analytics', 'Login Portal', 'Copy for the control benefit tile on the admin login portal.'),
('admin_login_automation_title', 'Admin Login Automation Benefit Title', 'Efficient', 'Login Portal', 'Title for the automation benefit tile on the admin login portal.'),
('admin_login_automation_copy', 'Admin Login Automation Benefit Copy', 'Automate and simplify operations', 'Login Portal', 'Copy for the automation benefit tile on the admin login portal.'),
('admin_login_reliable_title', 'Admin Login Reliable Benefit Title', 'Compliant', 'Login Portal', 'Title for the reliable benefit tile on the admin login portal.'),
('admin_login_reliable_copy', 'Admin Login Reliable Benefit Copy', 'Meet regulatory requirements', 'Login Portal', 'Copy for the reliable benefit tile on the admin login portal.')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);
